MVCCalculator/Models/CalculatorModel.cs
using System.Collections.Generic;
using System.Web.Mvc;

namespace MvcCalculator.Models
{
    public class CalculatorModel
    {
        public CalculatorModel()
        {
            Operaciones = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "+",
                    Value = "suma"
                },
                new SelectListItem
                {
                    Text = "-",
                    Value = "resta"
                },
                new SelectListItem
                {
                    Text = "x",
                    Value = "multiplicacion"
                },
                new SelectListItem
                {
                    Text = "/",
                    Value = "division"
                }
            };
        }

        public int Operador1 { get; set; }
        public int Operador2 { get; set; }
        public string Operacion { get; set; }
        public int Resultado { get; set; }
        public List<SelectListItem> Operaciones { get; set; }
    }
}

MVCCalculator/Controllers/CalculatorController.cs
using System.Web.Mvc;
using Calculator;
using MvcCalculator.Models;

namespace MvcCalculator.Controllers
{
    public class CalculatorController : Controller
    {
        public ActionResult Index()
        {
            return View(new CalculatorModel());
        }

        [HttpPost]
        public ActionResult Resultado(CalculatorModel model)
        {
            var calculatorUI = new CalculatorUi(new Calculator.Calculator());
            model.Resultado = calculatorUI.Operacion(model.Operacion, model.Operador1, model.Operador2);
            return View("Index", model);
        }
    }
}

MVCCalculator/Views/Calculator/Index.cshtml
@model MvcCalculator.Models.CalculatorModel

<h2>Calculator</h2>

@using (Html.BeginForm("Resultado", "Calculator", FormMethod.Post))
{
    <div>
        @Html.EditorFor(model=>model.Operador1)
    </div>
    <div>
        @Html.DropDownList("Operacion", Model.Operaciones, "", Model.Operacion)
    </div>
    <div>
        @Html.EditorFor(model => model.Operador2)
    </div>
    <div>
        =
    </div>
    <div id="resultdo">
        @Model.Resultado
    </div>

  <input type="submit" value="obtener resultado" />
}